[theme]
primaryColor = "#1E88E5"   # Blue shade for primary elements
backgroundColor = "#FFFFFF" # White background
secondaryBackgroundColor = "#F0F2F6" # Light gray for secondary elements
textColor = "#262730"       # Dark gray for text
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false